Added explicit responses
dotchetter/RobBotTheRobot pull request #2
Opened 2019-10-08 13:36 UTC by gustavakerstrom99

2019-10-10 13:13 UTC, dotchetter commented on source/robbot.py
> +        self._explicitAdjectives = [
Nice, kommer skriva om denna lista till en Tuple eftersom den är en icke-muterande struktur.
Kommer lägga den som en klassvariabel istället för instansvariabel då samma gjorts med self._keywords i senaste commiten.

2019-10-11 00:14 UTC, dotchetter requested changes
Nu har jag läst igenom hela PR'en. Funktionen kommer mergas, men innan dess får du gärna;

1. Skriva om koden så att responserna inte är hårdkodade utan läses in från filen explicit_responses.dat
2. använda snake_case i projektet för enhetlig kodstil
3. Pusha gärna inte utkommenterad kod.

2019-10-15 10:33 UTC, gustavakerstrom99 commented
fixade det

2019-10-22 17:43 UTC, dotchetter approved these changes

2019-10-22 17:44 UTC, dotchetter commented
Snyggt, lägger in detta i projektet.

2019-10-22 17:59 UTC, merged